apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: expansion-vm
  namespace: pvc-expansion-demo
spec:
  instancetype:
    name: u1.small
  preference:
    name: fedora
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: expansion-vm
    spec:
      domain:
        devices:
          disks:
          - disk: {}
            name: rootdisk
          - disk: {}
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        dataVolume:
          name: expansion-vm-rootdisk
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: redhat
            chpasswd:
              expire: false
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: expansion-vm-rootdisk
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: lvms-vg1
