apiVersion: v1
kind: Service
metadata:
  name: windows-ssh-nodeport
spec:
  type: NodePort
  selector:
    vm.kubevirt.io/name: <your-windows-vm-name>
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022
