apiVersion: v1
kind: Service
metadata:
  name: windows-ssh-lb
spec:
  type: LoadBalancer
  selector:
    vm.kubevirt.io/name: <your-windows-vm-name>
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
