apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-shared-cephfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-cephfs
