apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-vm-odf
  namespace: default
spec:
  instancetype:
    name: u1.small
  preference:
    name: fedora
  runStrategy: Halted
  template:
    metadata:
      labels:
        kubevirt.io/vm: test-vm-odf
    spec:
      domain:
        devices:
          disks:
          - disk: {}
            name: boot-disk
          interfaces:
          - masquerade: {}
            name: default
      networks:
      - name: default
        pod: {}
      volumes:
      - name: boot-disk
        dataVolume:
          name: test-vm-odf-boot
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: test-vm-odf-boot
    spec:
      source:
        registry:
          url: docker://quay.io/containerdisks/fedora:latest
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ocs-storagecluster-ceph-rbd
