apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-app-vm
  namespace: myapp
  labels:
    app: myapp
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - metadata:
        name: fedora-app-vm-volume
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  instancetype:
    name: u1.large
  preference:
    name: fedora
  template:
    metadata:
      labels:
        kubevirt.io/domain: fedora-app-vm
        app: myapp
    spec:
      domain:
        devices:
          disks:
            - disk: {}
              name: rootdisk
            - disk: {}
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: fedora-app-vm-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora
              chpasswd:
                expire: false
              ssh_pwauth: true
          name: cloudinitdisk
