apiVersion: v1
kind: Service
metadata:
  name: dualstack-web
  namespace: dualstack-demo
spec:
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: dualstack-vm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
