apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: dualstack-udn
  namespace: dualstack-demo
spec:
  topology: Layer2
  layer2:
    role: Primary
    subnets:
      - "10.200.0.0/16"
      - "2001:db8:abcd::/64"
    ipam:
      lifecycle: Persistent
