apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: dualstack-vm
  namespace: dualstack-demo
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app: dualstack-vm
    spec:
      domain:
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - port: 80
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:40
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: changeme
              chpasswd:
                expire: false
              packages:
                - nginx
              runcmd:
                - systemctl enable --now nginx
            networkData: |
              version: 2
              ethernets:
                eth0:
                  dhcp4: true
                  addresses: [ fd10:0:2::2/120 ]
                  gateway6: fd10:0:2::1
