apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: debian-cloudinit
  namespace: qemu-ga-demo
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - metadata:
        name: debian-cloudinit-rootdisk
      spec:
        storage:
          resources:
            requests:
              storage: 10Gi
          accessModes:
            - ReadWriteOnce
        source:
          registry:
            url: docker://quay.io/ocpv_cookbook/debian-no-qga:latest
  template:
    metadata:
      labels:
        app: debian-cloudinit
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          dataVolume:
            name: debian-cloudinit-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: debian
              password: debian
              chpasswd: { expire: false }
              packages:
                - qemu-guest-agent
              runcmd:
                - systemctl enable --now qemu-guest-agent
