apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: monitoring-test-vm
  namespace: vm-monitoring-demo
  labels:
    app: monitoring-demo
spec:
  instancetype:
    name: u1.small
  preference:
    name: fedora
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: monitoring-test-vm
    spec:
      domain:
        devices:
          disks:
          - disk: {}
            name: rootdisk
          - disk: {}
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:latest
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: redhat
            chpasswd:
              expire: false
            packages:
            - qemu-guest-agent
            runcmd:
            - systemctl enable --now qemu-guest-agent
