apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-realtime
  namespace: realtime-demo
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-realtime
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker-rt: ""
      domain:
        cpu:
          model: host-passthrough
          sockets: 1
          cores: 2
          threads: 1
          dedicatedCpuPlacement: true
          isolateEmulatorThread: true
          ioThreadsPolicy: auto
          numa:
            guestMappingPassthrough: {}
          realtime:
            mask: "0"
        memory:
          hugepages:
            pageSize: 1Gi
        resources:
          requests:
            memory: 2Gi
            cpu: 2
          limits:
            memory: 2Gi
            cpu: 2
        devices:
          autoattachSerialConsole: true
          autoattachMemBalloon: false
          autoattachGraphicsDevice: false
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: rootdisk
        dataVolume:
          name: vm-realtime
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: fedora
            password: redhat
            chpasswd:
              expire: false
            ssh_pwauth: true
  dataVolumeTemplates:
  - metadata:
      name: vm-realtime
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources:
          requests:
            storage: 30Gi
