apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: web-vm
  namespace: metallb-demo
  labels:
    app: web-vm
spec:
  runStrategy: Always
  instancetype:
    name: u1.small
  preference:
    name: fedora
  template:
    metadata:
      labels:
        app: web-vm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk: {}
            - name: cloudinitdisk
              disk: {}
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:40
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: changeme
              chpasswd:
                expire: false
              ssh_pwauth: true
              packages:
                - nginx
              runcmd:
                - systemctl enable --now nginx
