apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: gpu-workload-vm
  namespace: vm-placement
spec:
  runStrategy: Manual
  instancetype:
    name: u1.large
  preference:
    name: fedora
  template:
    metadata:
      labels:
        app: ml-training
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: gpu
                    operator: In
                    values:
                      - nvidia-t4
                      - nvidia-a100
                  - key: env
                    operator: In
                    values:
                      - production
      domain:
        devices:
          disks:
            - name: rootdisk
              disk: {}
            - name: cloudinitdisk
              disk: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:43
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: fedora
              chpasswd:
                expire: false
