apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: web-vm
  namespace: vm-placement
spec:
  runStrategy: Manual
  instancetype:
    name: u1.large
  preference:
    name: fedora
  template:
    metadata:
      labels:
        app: webserver
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: storage
                    operator: In
                    values:
                      - nvme
            - weight: 50
              preference:
                matchExpressions:
                  - key: storage
                    operator: In
                    values:
                      - ssd
      domain:
        devices:
          disks:
            - name: rootdisk
              disk: {}
            - name: cloudinitdisk
              disk: {}
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:43
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: fedora
              chpasswd:
                expire: false
