apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-bridge-demo
  namespace: bridge-demo
  labels:
    app: fedora-bridge-demo
spec:
  runStrategy: Always
  dataVolumeTemplates:
  - metadata:
      name: fedora-bridge-demo-root
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources:
          requests:
            storage: 30Gi
  instancetype:
    name: u1.large
  preference:
    name: fedora
  template:
    metadata:
      labels:
        app: fedora-bridge-demo
    spec:
      domain:
        devices:
          disks:
          - name: fedora-bridge-demo-root
            disk: {}
          - name: cloudinitdisk
            disk: {}
          interfaces:
          - masquerade: {}
            name: default
          - bridge: {}
            name: nic-linux-bridge
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: lnbr0-bridge
        name: nic-linux-bridge
      volumes:
      - name: fedora-bridge-demo-root
        dataVolume:
          name: fedora-bridge-demo-root
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              enp2s0:
                addresses:
                - 192.168.50.10/24
          userData: |
            #cloud-config
            user: fedora
            password: fedora
            chpasswd:
              expire: false
