apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: mlx-sriov-policy
  namespace: openshift-sriov-network-operator
spec:
  resourceName: mlxsriovnic
  nodeSelector:
    kubernetes.io/hostname: <node-name>
  numVfs: 4
  nicSelector:
    vendor: "15b3"
    deviceID: "1015"
    pfNames:
    - enp11s0f0np0
  deviceType: vfio-pci
  isRdma: false
