apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: migratable-vm
  namespace: live-migration-demo
spec:
  runStrategy: Always
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: migratable-vm-disk
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 30Gi
          storageClassName: nfs-storage
  template:
    metadata:
      labels:
        kubevirt.io/domain: migratable-vm
    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 1
        memory:
          guest: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade:
          rng:
        machine:
          type: pc-q35-rhel9.4.0
      networks:
        - name: default
          pod:
      volumes:
        - name: rootdisk
          dataVolume:
            name: migratable-vm-disk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora123
              chpasswd:
                expire: false
              ssh_pwauth: true
