apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win2k25-vm-1
  namespace: default
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: win2k25-vm-1-disk
      spec:
        sourceRef:
          kind: DataSource
          name: win2k25
          namespace: default
        storage:
          resources:
            requests:
              storage: 60Gi
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/domain: win2k25-vm-1
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 2
        memory:
          guest: 4Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: sysprep
              cdrom:
                bus: sata
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
          tpm: {}
          rng: {}
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            spinlocks:
              spinlocks: 8191
            vpindex: {}
            runtime: {}
            synic: {}
            stimer: {}
            reset: {}
            frequencies: {}
            reenlightenment: {}
            tlbflush: {}
            ipi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: win2k25-vm-1-disk
        - name: sysprep
          sysprep:
            configMap:
              name: win2k25-sysprep-unattend
