apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: hpp-test-vm
  namespace: default
spec:
  instancetype:
    name: u1.small
  preference:
    name: fedora
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: hpp-test-vm
    spec:
      domain:
        devices:
          disks:
          - disk: {}
            name: rootdisk
          - disk: {}
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        dataVolume:
          name: hpp-test-vm-rootdisk
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: fedora
            password: fedora
            chpasswd:
              expire: false
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: hpp-test-vm-rootdisk
    spec:
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: hostpath-csi
      source:
        registry:
          url: docker://quay.io/containerdisks/fedora:latest
