apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: my-linux-server
  namespace: instancetype-demo
spec:
  cpu:
    preferredCPUTopology: cores
  firmware:
    preferredUseEfi: true
    preferredUseSecureBoot: false
  devices:
    preferredDiskBus: virtio
    preferredInterfaceModel: virtio
